# Generated by Django 2.1.5 on 2019-02-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190221_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('start', models.TimeField(verbose_name='inínio')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('speakers', models.ManyToManyField(to='core.Speaker')),
            ],
        ),
    ]
